theme = "after-dark"
baseURL = "/"
languageCode = "en-us"
title = ">jesse-tweedle"
theme_variant = "standard"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]
description = "Hello, I exist."
enableEmoji = true
googleAnalytics = 'UA-84762908-2'

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Github"
  weight = 3
  identifier = "github"
  url = "https://github.com/tweed1e"
[[menu.main]]
  name = "Twitter"
  weight = 3
  identifier = "twitter"
  url = "https://twitter.com/tweed1e"